language: python
python:
  - "3.1"
  - "3.6"      # current default Python on Travis CI
# - "3.7"
# - "3.8"
# - "3.9"
# - "3.9-dev"  # 3.9 development branch
# - "nightly"  # nightly build
install:
  - pip install flake8
  - pip3 install .
before_script:
# ignore W191 (tabs instead of spacese)
# ignore E501 (lines > 80 char)
  - flake8 --extend-ignore=W191,E501 .
script:
  - pytest
